require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "test/tmp/**/*"
    - "**/vendor/**/*"
    - "**/node_modules/**/*"

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
    - "spec/**/*"
    - "Guardfile"

Metrics/MethodLength:
  Max: 12

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/*"

Rails/OutputSafety:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/MutableConstant:
  Enabled: true
  SafeAutoCorrect: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"
    "%W": "()"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
